// Generated by tools/generate_shape_catalog.py from catalog/shape_catalog.json.
// Do not edit by hand.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace minescript_miner {

inline constexpr int SHAPE_CATALOG_VERSION = 2;
inline constexpr int GEOMETRY_CATALOG_VERSION = 2;
inline constexpr int GEOMETRY_SHAPE_CATALOG_VERSION = SHAPE_CATALOG_VERSION;
inline constexpr std::size_t GEOMETRY_SHAPE_COUNT = 106;
inline constexpr std::size_t GEOMETRY_BOX_COUNT = 249;
inline constexpr std::size_t GEOMETRY_FACE_COUNT = 1246;

inline constexpr std::int32_t SHAPE_EMPTY = 0;
inline constexpr std::int32_t SHAPE_FULL_CUBE = 1;
inline constexpr std::int32_t SHAPE_SLAB_BOTTOM = 2;
inline constexpr std::int32_t SHAPE_SLAB_TOP = 3;

enum class PlaneAxis : std::int32_t {
    X = 0,
    Y = 1,
    Z = 2,
};

struct Aabb16 {
    std::uint8_t min_x;
    std::uint8_t min_y;
    std::uint8_t min_z;
    std::uint8_t max_x;
    std::uint8_t max_y;
    std::uint8_t max_z;
};

struct RectFace16 {
    PlaneAxis axis;
    std::uint8_t coord;
    std::uint8_t u_min;
    std::uint8_t u_max;
    std::uint8_t v_min;
    std::uint8_t v_max;
    std::int8_t normal_sign;
};

struct ShapeGeometry {
    std::uint16_t face_offset;
    std::uint8_t face_count;
};

struct GeometryCatalog {
    std::array<const char *, GEOMETRY_SHAPE_COUNT> shape_names;
    std::array<ShapeGeometry, GEOMETRY_SHAPE_COUNT> shapes;
    std::array<RectFace16, GEOMETRY_FACE_COUNT> faces;
};

const GeometryCatalog &geometry_catalog();
const ShapeGeometry &geometry_for_shape(std::int32_t shape_id);
std::int32_t geometry_catalog_shape_count();

const char *shape_id_name(std::int32_t shape_id);
std::uint8_t shape_box_count(std::int32_t shape_id);
std::int32_t shape_count();
const std::array<const char *, GEOMETRY_SHAPE_COUNT> &shape_names();

inline bool is_empty_shape(std::int32_t shape_id) {
    return shape_id == SHAPE_EMPTY;
}

}
