// Generated by tools/generate_shape_catalog.py from catalog/shape_catalog.json.
// Do not edit by hand.

#include "minescript_miner/geometry_catalog.hpp"

#include <array>
#include <cstddef>
#include <cstdint>

namespace minescript_miner {

namespace {

constexpr std::array<const char *, GEOMETRY_SHAPE_COUNT> SHAPE_NAME_TABLE = {
    "empty",
    "full_cube",
    "slab_bottom",
    "slab_top",
    "stairs_north_bottom_straight",
    "stairs_north_bottom_inner_left",
    "stairs_north_bottom_inner_right",
    "stairs_north_bottom_outer_left",
    "stairs_north_bottom_outer_right",
    "stairs_north_top_straight",
    "stairs_north_top_inner_left",
    "stairs_north_top_inner_right",
    "stairs_north_top_outer_left",
    "stairs_north_top_outer_right",
    "stairs_east_bottom_straight",
    "stairs_east_bottom_inner_left",
    "stairs_east_bottom_inner_right",
    "stairs_east_bottom_outer_left",
    "stairs_east_bottom_outer_right",
    "stairs_east_top_straight",
    "stairs_east_top_inner_left",
    "stairs_east_top_inner_right",
    "stairs_east_top_outer_left",
    "stairs_east_top_outer_right",
    "stairs_south_bottom_straight",
    "stairs_south_bottom_inner_left",
    "stairs_south_bottom_inner_right",
    "stairs_south_bottom_outer_left",
    "stairs_south_bottom_outer_right",
    "stairs_south_top_straight",
    "stairs_south_top_inner_left",
    "stairs_south_top_inner_right",
    "stairs_south_top_outer_left",
    "stairs_south_top_outer_right",
    "stairs_west_bottom_straight",
    "stairs_west_bottom_inner_left",
    "stairs_west_bottom_inner_right",
    "stairs_west_bottom_outer_left",
    "stairs_west_bottom_outer_right",
    "stairs_west_top_straight",
    "stairs_west_top_inner_left",
    "stairs_west_top_inner_right",
    "stairs_west_top_outer_left",
    "stairs_west_top_outer_right",
    "pane_none",
    "pane_north",
    "pane_east",
    "pane_north_east",
    "pane_south",
    "pane_north_south",
    "pane_east_south",
    "pane_north_east_south",
    "pane_west",
    "pane_north_west",
    "pane_east_west",
    "pane_north_east_west",
    "pane_south_west",
    "pane_north_south_west",
    "pane_east_south_west",
    "pane_north_east_south_west",
    "fence_none",
    "fence_north",
    "fence_east",
    "fence_north_east",
    "fence_south",
    "fence_north_south",
    "fence_east_south",
    "fence_north_east_south",
    "fence_west",
    "fence_north_west",
    "fence_east_west",
    "fence_north_east_west",
    "fence_south_west",
    "fence_north_south_west",
    "fence_east_south_west",
    "fence_north_east_south_west"
};

enum Direction : std::uint8_t {
    NORTH = 0,
    EAST = 1,
    SOUTH = 2,
    WEST = 3,
};

enum StairShape : std::uint8_t {
    STRAIGHT = 0,
    INNER_LEFT = 1,
    INNER_RIGHT = 2,
    OUTER_LEFT = 3,
    OUTER_RIGHT = 4,
};

struct Range16 {
    std::uint8_t min;
    std::uint8_t max;
};

struct AxisPair {
    PlaneAxis first;
    PlaneAxis second;
};

struct BoxList {
    std::array<Aabb16, 5> boxes{};
    std::uint8_t count = 0;
};

struct SplitList {
    std::array<std::uint8_t, 12> values{};
    std::uint8_t count = 0;
};

struct CatalogBuilder {
    GeometryCatalog catalog{};
    std::uint16_t shape_count = 0;
    std::uint16_t box_count = 0;
    std::uint16_t face_count = 0;
};

constexpr Aabb16 box(
    std::uint8_t min_x,
    std::uint8_t min_y,
    std::uint8_t min_z,
    std::uint8_t max_x,
    std::uint8_t max_y,
    std::uint8_t max_z
) {
    return {min_x, min_y, min_z, max_x, max_y, max_z};
}

constexpr std::uint8_t min_u8(std::uint8_t a, std::uint8_t b) {
    return a < b ? a : b;
}

constexpr std::uint8_t max_u8(std::uint8_t a, std::uint8_t b) {
    return a > b ? a : b;
}

constexpr std::uint8_t axis_min(const Aabb16 &b, PlaneAxis axis) {
    switch (axis) {
        case PlaneAxis::X:
            return b.min_x;
        case PlaneAxis::Y:
            return b.min_y;
        case PlaneAxis::Z:
            return b.min_z;
    }
    return 0;
}

constexpr std::uint8_t axis_max(const Aabb16 &b, PlaneAxis axis) {
    switch (axis) {
        case PlaneAxis::X:
            return b.max_x;
        case PlaneAxis::Y:
            return b.max_y;
        case PlaneAxis::Z:
            return b.max_z;
    }
    return 0;
}

constexpr AxisPair uv_axes(PlaneAxis axis) {
    switch (axis) {
        case PlaneAxis::X:
            return {PlaneAxis::Y, PlaneAxis::Z};
        case PlaneAxis::Y:
            return {PlaneAxis::X, PlaneAxis::Z};
        case PlaneAxis::Z:
            return {PlaneAxis::X, PlaneAxis::Y};
    }
    return {PlaneAxis::X, PlaneAxis::Y};
}

constexpr bool overlaps_1d(std::uint8_t a_min, std::uint8_t a_max, std::uint8_t b_min, std::uint8_t b_max) {
    return a_min < b_max && b_min < a_max;
}

constexpr void add_box(BoxList &shape, Aabb16 b) {
    shape.boxes[shape.count] = b;
    ++shape.count;
}

constexpr void add_split(SplitList &splits, std::uint8_t value, std::uint8_t min_value, std::uint8_t max_value) {
    if (value > min_value && value < max_value) {
        splits.values[splits.count] = value;
        ++splits.count;
    }
}

constexpr void sort_unique(SplitList &splits) {
    for (std::uint8_t i = 1; i < splits.count; ++i) {
        const std::uint8_t value = splits.values[i];
        std::uint8_t j = i;
        while (j > 0 && splits.values[j - 1] > value) {
            splits.values[j] = splits.values[j - 1];
            --j;
        }
        splits.values[j] = value;
    }

    std::uint8_t write_index = 0;
    for (std::uint8_t read_index = 0; read_index < splits.count; ++read_index) {
        if (write_index == 0 || splits.values[read_index] != splits.values[write_index - 1]) {
            splits.values[write_index] = splits.values[read_index];
            ++write_index;
        }
    }
    splits.count = write_index;
}

constexpr bool midpoint_inside(std::uint8_t min_value, std::uint8_t max_value, std::uint16_t midpoint_times_2) {
    return static_cast<std::uint16_t>(min_value) * 2 < midpoint_times_2 &&
           midpoint_times_2 < static_cast<std::uint16_t>(max_value) * 2;
}

constexpr bool outside_occupied(
    const RectFace16 &face,
    std::uint16_t u_midpoint_times_2,
    std::uint16_t v_midpoint_times_2,
    const BoxList &shape
) {
    const AxisPair axes = uv_axes(face.axis);
    for (std::uint8_t i = 0; i < shape.count; ++i) {
        const Aabb16 &b = shape.boxes[i];
        const bool crosses_face =
            face.normal_sign > 0
                ? axis_min(b, face.axis) <= face.coord && axis_max(b, face.axis) > face.coord
                : axis_min(b, face.axis) < face.coord && axis_max(b, face.axis) >= face.coord;
        if (!crosses_face) {
            continue;
        }

        if (midpoint_inside(axis_min(b, axes.first), axis_max(b, axes.first), u_midpoint_times_2) &&
            midpoint_inside(axis_min(b, axes.second), axis_max(b, axes.second), v_midpoint_times_2)) {
            return true;
        }
    }
    return false;
}

constexpr void add_face(CatalogBuilder &builder, RectFace16 face) {
    builder.catalog.faces[builder.face_count] = face;
    ++builder.face_count;
}

constexpr void add_face_cells(CatalogBuilder &builder, const RectFace16 &face, const BoxList &shape) {
    const AxisPair axes = uv_axes(face.axis);
    SplitList u_splits{};
    SplitList v_splits{};
    u_splits.values[u_splits.count++] = face.u_min;
    u_splits.values[u_splits.count++] = face.u_max;
    v_splits.values[v_splits.count++] = face.v_min;
    v_splits.values[v_splits.count++] = face.v_max;

    for (std::uint8_t i = 0; i < shape.count; ++i) {
        const Aabb16 &b = shape.boxes[i];
        if (axis_min(b, face.axis) > face.coord || axis_max(b, face.axis) < face.coord) {
            continue;
        }

        const std::uint8_t box_u_min = axis_min(b, axes.first);
        const std::uint8_t box_u_max = axis_max(b, axes.first);
        const std::uint8_t box_v_min = axis_min(b, axes.second);
        const std::uint8_t box_v_max = axis_max(b, axes.second);
        if (!overlaps_1d(face.u_min, face.u_max, box_u_min, box_u_max) ||
            !overlaps_1d(face.v_min, face.v_max, box_v_min, box_v_max)) {
            continue;
        }

        add_split(u_splits, box_u_min, face.u_min, face.u_max);
        add_split(u_splits, box_u_max, face.u_min, face.u_max);
        add_split(v_splits, box_v_min, face.v_min, face.v_max);
        add_split(v_splits, box_v_max, face.v_min, face.v_max);
    }

    sort_unique(u_splits);
    sort_unique(v_splits);

    for (std::uint8_t u_index = 0; u_index + 1 < u_splits.count; ++u_index) {
        for (std::uint8_t v_index = 0; v_index + 1 < v_splits.count; ++v_index) {
            const std::uint8_t u_min = u_splits.values[u_index];
            const std::uint8_t u_max = u_splits.values[u_index + 1];
            const std::uint8_t v_min = v_splits.values[v_index];
            const std::uint8_t v_max = v_splits.values[v_index + 1];
            if (u_max <= u_min || v_max <= v_min) {
                continue;
            }

            const std::uint16_t u_midpoint_times_2 = static_cast<std::uint16_t>(u_min) + u_max;
            const std::uint16_t v_midpoint_times_2 = static_cast<std::uint16_t>(v_min) + v_max;
            if (outside_occupied(face, u_midpoint_times_2, v_midpoint_times_2, shape)) {
                continue;
            }

            add_face(builder, {face.axis, face.coord, u_min, u_max, v_min, v_max, face.normal_sign});
        }
    }
}

constexpr void add_box_faces(CatalogBuilder &builder, const Aabb16 &b, const BoxList &shape) {
    add_face_cells(builder, {PlaneAxis::X, b.min_x, b.min_y, b.max_y, b.min_z, b.max_z, -1}, shape);
    add_face_cells(builder, {PlaneAxis::X, b.max_x, b.min_y, b.max_y, b.min_z, b.max_z, 1}, shape);
    add_face_cells(builder, {PlaneAxis::Y, b.min_y, b.min_x, b.max_x, b.min_z, b.max_z, -1}, shape);
    add_face_cells(builder, {PlaneAxis::Y, b.max_y, b.min_x, b.max_x, b.min_z, b.max_z, 1}, shape);
    add_face_cells(builder, {PlaneAxis::Z, b.min_z, b.min_x, b.max_x, b.min_y, b.max_y, -1}, shape);
    add_face_cells(builder, {PlaneAxis::Z, b.max_z, b.min_x, b.max_x, b.min_y, b.max_y, 1}, shape);
}

constexpr void add_shape(CatalogBuilder &builder, const BoxList &shape) {
    const std::uint16_t box_offset = builder.box_count;
    const std::uint16_t face_offset = builder.face_count;

    for (std::uint8_t i = 0; i < shape.count; ++i) {
        builder.catalog.boxes[builder.box_count] = shape.boxes[i];
        ++builder.box_count;
    }
    for (std::uint8_t i = 0; i < shape.count; ++i) {
        add_box_faces(builder, shape.boxes[i], shape);
    }

    builder.catalog.shapes[builder.shape_count] = {
        box_offset,
        shape.count,
        face_offset,
        static_cast<std::uint8_t>(builder.face_count - face_offset),
    };
    ++builder.shape_count;
}

constexpr Range16 half_bounds_1d(Direction direction, bool front, bool x_axis) {
    switch (direction) {
        case NORTH:
            return x_axis ? Range16{0, 16} : (front ? Range16{0, 8} : Range16{8, 16});
        case SOUTH:
            return x_axis ? Range16{0, 16} : (front ? Range16{8, 16} : Range16{0, 8});
        case EAST:
            return x_axis ? (front ? Range16{8, 16} : Range16{0, 8}) : Range16{0, 16};
        case WEST:
            return x_axis ? (front ? Range16{0, 8} : Range16{8, 16}) : Range16{0, 16};
    }
    return {0, 16};
}

constexpr Direction lateral_direction(Direction direction, bool left) {
    if (left) {
        switch (direction) {
            case NORTH:
                return WEST;
            case EAST:
                return NORTH;
            case SOUTH:
                return EAST;
            case WEST:
                return SOUTH;
        }
    }

    switch (direction) {
        case NORTH:
            return EAST;
        case EAST:
            return SOUTH;
        case SOUTH:
            return WEST;
        case WEST:
            return NORTH;
    }
    return NORTH;
}

constexpr Aabb16 stair_quadrant(Direction direction, bool left, bool front, std::uint8_t y_min, std::uint8_t y_max) {
    const Range16 front_x = half_bounds_1d(direction, front, true);
    const Range16 front_z = half_bounds_1d(direction, front, false);
    const Direction lateral = lateral_direction(direction, left);
    const Range16 lateral_x = half_bounds_1d(lateral, true, true);
    const Range16 lateral_z = half_bounds_1d(lateral, true, false);
    return box(
        max_u8(front_x.min, lateral_x.min),
        y_min,
        max_u8(front_z.min, lateral_z.min),
        min_u8(front_x.max, lateral_x.max),
        y_max,
        min_u8(front_z.max, lateral_z.max)
    );
}

constexpr BoxList stair_boxes(Direction direction, bool top, StairShape stair_shape) {
    BoxList shape{};
    std::uint8_t y_min = 8;
    std::uint8_t y_max = 16;
    if (top) {
        add_box(shape, box(0, 8, 0, 16, 16, 16));
        y_min = 0;
        y_max = 8;
    } else {
        add_box(shape, box(0, 0, 0, 16, 8, 16));
    }

    switch (stair_shape) {
        case STRAIGHT:
            add_box(shape, stair_quadrant(direction, true, true, y_min, y_max));
            add_box(shape, stair_quadrant(direction, false, true, y_min, y_max));
            break;
        case INNER_LEFT:
            add_box(shape, stair_quadrant(direction, true, true, y_min, y_max));
            add_box(shape, stair_quadrant(direction, false, true, y_min, y_max));
            add_box(shape, stair_quadrant(direction, true, false, y_min, y_max));
            break;
        case INNER_RIGHT:
            add_box(shape, stair_quadrant(direction, true, true, y_min, y_max));
            add_box(shape, stair_quadrant(direction, false, true, y_min, y_max));
            add_box(shape, stair_quadrant(direction, false, false, y_min, y_max));
            break;
        case OUTER_LEFT:
            add_box(shape, stair_quadrant(direction, true, true, y_min, y_max));
            break;
        case OUTER_RIGHT:
            add_box(shape, stair_quadrant(direction, false, true, y_min, y_max));
            break;
    }
    return shape;
}

constexpr BoxList connection_boxes(int mask, std::uint8_t center_min, std::uint8_t center_max) {
    BoxList shape{};
    add_box(shape, box(center_min, 0, center_min, center_max, 16, center_max));
    if ((mask & 1) != 0) {
        add_box(shape, box(center_min, 0, 0, center_max, 16, center_min));
    }
    if ((mask & 2) != 0) {
        add_box(shape, box(center_max, 0, center_min, 16, 16, center_max));
    }
    if ((mask & 4) != 0) {
        add_box(shape, box(center_min, 0, center_max, center_max, 16, 16));
    }
    if ((mask & 8) != 0) {
        add_box(shape, box(0, 0, center_min, center_min, 16, center_max));
    }
    return shape;
}

constexpr GeometryCatalog build_geometry_catalog() {
    CatalogBuilder builder{};
    builder.catalog.shape_names = SHAPE_NAME_TABLE;

    add_shape(builder, BoxList{});

    BoxList full_cube{};
    add_box(full_cube, box(0, 0, 0, 16, 16, 16));
    add_shape(builder, full_cube);

    BoxList slab_bottom{};
    add_box(slab_bottom, box(0, 0, 0, 16, 8, 16));
    add_shape(builder, slab_bottom);

    BoxList slab_top{};
    add_box(slab_top, box(0, 8, 0, 16, 16, 16));
    add_shape(builder, slab_top);

    for (std::uint8_t direction = 0; direction < 4; ++direction) {
        for (std::uint8_t half = 0; half < 2; ++half) {
            for (std::uint8_t stair_shape = 0; stair_shape < 5; ++stair_shape) {
                add_shape(
                    builder,
                    stair_boxes(
                        static_cast<Direction>(direction),
                        half == 1,
                        static_cast<StairShape>(stair_shape)
                    )
                );
            }
        }
    }

    for (int mask = 0; mask < 16; ++mask) {
        add_shape(builder, connection_boxes(mask, 7, 9));
    }

    for (int mask = 0; mask < 16; ++mask) {
        add_shape(builder, connection_boxes(mask, 6, 10));
    }

    return builder.catalog;
}

constexpr GeometryCatalog CATALOG = build_geometry_catalog();

constexpr std::uint32_t used_box_count() {
    std::uint32_t total = 0;
    for (const ShapeGeometry &shape : CATALOG.shapes) {
        total += shape.box_count;
    }
    return total;
}

constexpr std::uint32_t used_face_count() {
    std::uint32_t total = 0;
    for (const ShapeGeometry &shape : CATALOG.shapes) {
        total += shape.face_count;
    }
    return total;
}

static_assert(used_box_count() == GEOMETRY_BOX_COUNT, "geometry box count changed");
static_assert(used_face_count() == GEOMETRY_FACE_COUNT, "geometry face count changed");

}  // namespace

const GeometryCatalog &geometry_catalog() {
    return CATALOG;
}

const ShapeGeometry &geometry_for_shape(std::int32_t shape_id) {
    if (shape_id < 0 || static_cast<std::size_t>(shape_id) >= CATALOG.shapes.size()) {
        return CATALOG.shapes[static_cast<std::size_t>(SHAPE_FULL_CUBE)];
    }
    return CATALOG.shapes[static_cast<std::size_t>(shape_id)];
}

std::int32_t geometry_catalog_shape_count() {
    return static_cast<std::int32_t>(CATALOG.shapes.size());
}

const std::array<const char *, GEOMETRY_SHAPE_COUNT> &shape_names() {
    return CATALOG.shape_names;
}

const char *shape_id_name(std::int32_t shape_id) {
    if (shape_id < 0 || static_cast<std::size_t>(shape_id) >= CATALOG.shape_names.size()) {
        return "unknown_shape";
    }
    return CATALOG.shape_names[static_cast<std::size_t>(shape_id)];
}

std::int32_t shape_count() {
    return static_cast<std::int32_t>(CATALOG.shape_names.size());
}

}
