// Generated by tools/generate_shape_catalog.py from catalog/shape_catalog.json.
// Catalog compatibility constants. Do not edit by hand.

#pragma once

#include <cstddef>
#include <cstdint>

namespace minecraft_miner {

inline constexpr int SHAPE_CATALOG_VERSION = 3;
inline constexpr int GEOMETRY_CATALOG_VERSION = 3;
inline constexpr int GEOMETRY_SHAPE_CATALOG_VERSION = SHAPE_CATALOG_VERSION;
inline constexpr int BLOCK_SHAPE_MAPPING_VERSION = 3;
inline constexpr std::int32_t GEOMETRY_UNITS_PER_BLOCK = 32;
inline constexpr std::size_t GEOMETRY_SHAPE_COUNT = 106;
inline constexpr std::size_t GEOMETRY_BOX_COUNT = 249;
inline constexpr std::size_t GEOMETRY_FACE_COUNT = 1246;
inline constexpr int MAX_CUBE_SIDE = 39;

}
