"""Generated catalog compatibility constants.

Generated by tools/generate_shape_catalog.py from catalog/shape_catalog.json.
Do not edit by hand.
"""

SHAPE_CATALOG_VERSION = 3
BLOCK_SHAPE_MAPPING_VERSION = 3
CATALOG_VERSION = SHAPE_CATALOG_VERSION
MAX_CUBE_SIDE = 39
SHAPE_COUNT = 106
