"""Generated block-state string to stable native shape-id mapping.

Generated by tools/generate_shape_catalog.py from catalog/shape_catalog.json.
Do not edit by hand.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple


SHAPE_CATALOG_VERSION = 1
BLOCK_SHAPE_MAPPING_VERSION = 1
CATALOG_VERSION = SHAPE_CATALOG_VERSION

DIRECTIONS = ('north', 'east', 'south', 'west')
HALVES = ('bottom', 'top')
STAIR_SHAPES = ('straight', 'inner_left', 'inner_right', 'outer_left', 'outer_right')

EMPTY_BLOCKS = frozenset(['minecraft:air', 'minecraft:cave_air', 'minecraft:lava', 'minecraft:void_air', 'minecraft:water'])

BlockStateKey = Tuple[Tuple[str, str], ...]
BlockShapeKey = Tuple[str, BlockStateKey]


@dataclass(frozen=True)
class EncodedBlockRegion:
    shape_catalog_version: int
    block_shape_mapping_version: int
    side: int
    shape_ids: List[int]

    @property
    def catalog_version(self) -> int:
        return self.shape_catalog_version


def parse_block_state(block_string: Optional[str]) -> Tuple[str, BlockStateKey]:
    if block_string is None:
        return "minecraft:air", ()

    raw = block_string.strip().lower()
    if not raw:
        return "minecraft:air", ()

    if "[" not in raw or not raw.endswith("]"):
        return raw, ()

    block_type, properties_raw = raw.split("[", 1)
    properties_raw = properties_raw[:-1]
    properties = []
    for item in properties_raw.split(","):
        if "=" not in item:
            continue
        key, value = item.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key:
            properties.append((key, value))

    return block_type.strip(), tuple(sorted(properties))


def _state_key(*properties: Tuple[str, str]) -> BlockStateKey:
    return tuple(sorted(properties))


SHAPE_NAMES: List[str] = [
    'empty',
    'full_cube',
    'slab_bottom',
    'slab_top',
    'stairs_north_bottom_straight',
    'stairs_north_bottom_inner_left',
    'stairs_north_bottom_inner_right',
    'stairs_north_bottom_outer_left',
    'stairs_north_bottom_outer_right',
    'stairs_north_top_straight',
    'stairs_north_top_inner_left',
    'stairs_north_top_inner_right',
    'stairs_north_top_outer_left',
    'stairs_north_top_outer_right',
    'stairs_east_bottom_straight',
    'stairs_east_bottom_inner_left',
    'stairs_east_bottom_inner_right',
    'stairs_east_bottom_outer_left',
    'stairs_east_bottom_outer_right',
    'stairs_east_top_straight',
    'stairs_east_top_inner_left',
    'stairs_east_top_inner_right',
    'stairs_east_top_outer_left',
    'stairs_east_top_outer_right',
    'stairs_south_bottom_straight',
    'stairs_south_bottom_inner_left',
    'stairs_south_bottom_inner_right',
    'stairs_south_bottom_outer_left',
    'stairs_south_bottom_outer_right',
    'stairs_south_top_straight',
    'stairs_south_top_inner_left',
    'stairs_south_top_inner_right',
    'stairs_south_top_outer_left',
    'stairs_south_top_outer_right',
    'stairs_west_bottom_straight',
    'stairs_west_bottom_inner_left',
    'stairs_west_bottom_inner_right',
    'stairs_west_bottom_outer_left',
    'stairs_west_bottom_outer_right',
    'stairs_west_top_straight',
    'stairs_west_top_inner_left',
    'stairs_west_top_inner_right',
    'stairs_west_top_outer_left',
    'stairs_west_top_outer_right',
    'pane_none',
    'pane_north',
    'pane_east',
    'pane_north_east',
    'pane_south',
    'pane_north_south',
    'pane_east_south',
    'pane_north_east_south',
    'pane_west',
    'pane_north_west',
    'pane_east_west',
    'pane_north_east_west',
    'pane_south_west',
    'pane_north_south_west',
    'pane_east_south_west',
    'pane_north_east_south_west',
    'fence_none',
    'fence_north',
    'fence_east',
    'fence_north_east',
    'fence_south',
    'fence_north_south',
    'fence_east_south',
    'fence_north_east_south',
    'fence_west',
    'fence_north_west',
    'fence_east_west',
    'fence_north_east_west',
    'fence_south_west',
    'fence_north_south_west',
    'fence_east_south_west',
    'fence_north_east_south_west',
]
SHAPE_ID_BY_NAME: Dict[str, int] = {name: shape_id for shape_id, name in enumerate(SHAPE_NAMES)}
SHAPE_ID_BY_BLOCK_STATE: Dict[BlockShapeKey, int] = {
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 44,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 52,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 48,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 56,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 45,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 53,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 49,
    ('minecraft:glass_pane', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 57,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 46,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 54,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 50,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 58,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 47,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 55,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 51,
    ('minecraft:glass_pane', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 59,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 44,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 52,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 48,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 56,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 45,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 53,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 49,
    ('minecraft:iron_bars', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 57,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 46,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 54,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 50,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 58,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 47,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 55,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 51,
    ('minecraft:iron_bars', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 59,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 60,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 68,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 64,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 72,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 61,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 69,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 65,
    ('minecraft:oak_fence', (('east', 'false'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 73,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'false'))): 62,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'false'), ('south', 'false'), ('west', 'true'))): 70,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'false'))): 66,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'false'), ('south', 'true'), ('west', 'true'))): 74,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'false'))): 63,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'true'), ('south', 'false'), ('west', 'true'))): 71,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'false'))): 67,
    ('minecraft:oak_fence', (('east', 'true'), ('north', 'true'), ('south', 'true'), ('west', 'true'))): 75,
    ('minecraft:oak_slab', (('type', 'bottom'),)): 2,
    ('minecraft:oak_slab', (('type', 'double'),)): 1,
    ('minecraft:oak_slab', (('type', 'top'),)): 3,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'bottom'), ('shape', 'inner_left'))): 15,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'bottom'), ('shape', 'inner_right'))): 16,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'bottom'), ('shape', 'outer_left'))): 17,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'bottom'), ('shape', 'outer_right'))): 18,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'bottom'), ('shape', 'straight'))): 14,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'top'), ('shape', 'inner_left'))): 20,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'top'), ('shape', 'inner_right'))): 21,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'top'), ('shape', 'outer_left'))): 22,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'top'), ('shape', 'outer_right'))): 23,
    ('minecraft:oak_stairs', (('facing', 'east'), ('half', 'top'), ('shape', 'straight'))): 19,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'bottom'), ('shape', 'inner_left'))): 5,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'bottom'), ('shape', 'inner_right'))): 6,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'bottom'), ('shape', 'outer_left'))): 7,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'bottom'), ('shape', 'outer_right'))): 8,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'bottom'), ('shape', 'straight'))): 4,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'top'), ('shape', 'inner_left'))): 10,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'top'), ('shape', 'inner_right'))): 11,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'top'), ('shape', 'outer_left'))): 12,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'top'), ('shape', 'outer_right'))): 13,
    ('minecraft:oak_stairs', (('facing', 'north'), ('half', 'top'), ('shape', 'straight'))): 9,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'bottom'), ('shape', 'inner_left'))): 25,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'bottom'), ('shape', 'inner_right'))): 26,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'bottom'), ('shape', 'outer_left'))): 27,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'bottom'), ('shape', 'outer_right'))): 28,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'bottom'), ('shape', 'straight'))): 24,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'top'), ('shape', 'inner_left'))): 30,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'top'), ('shape', 'inner_right'))): 31,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'top'), ('shape', 'outer_left'))): 32,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'top'), ('shape', 'outer_right'))): 33,
    ('minecraft:oak_stairs', (('facing', 'south'), ('half', 'top'), ('shape', 'straight'))): 29,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'bottom'), ('shape', 'inner_left'))): 35,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'bottom'), ('shape', 'inner_right'))): 36,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'bottom'), ('shape', 'outer_left'))): 37,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'bottom'), ('shape', 'outer_right'))): 38,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'bottom'), ('shape', 'straight'))): 34,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'top'), ('shape', 'inner_left'))): 40,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'top'), ('shape', 'inner_right'))): 41,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'top'), ('shape', 'outer_left'))): 42,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'top'), ('shape', 'outer_right'))): 43,
    ('minecraft:oak_stairs', (('facing', 'west'), ('half', 'top'), ('shape', 'straight'))): 39,
}

SHAPE_EMPTY = SHAPE_ID_BY_NAME["empty"]
SHAPE_FULL_CUBE = SHAPE_ID_BY_NAME["full_cube"]
SHAPE_SLAB_BOTTOM = SHAPE_ID_BY_NAME["slab_bottom"]
SHAPE_SLAB_TOP = SHAPE_ID_BY_NAME["slab_top"]
SHAPE_COUNT = len(SHAPE_NAMES)

RELEVANT_PROPERTIES: Dict[str, Tuple[str, ...]] = {
    'minecraft:glass_pane': ('north', 'east', 'south', 'west'),
    'minecraft:iron_bars': ('north', 'east', 'south', 'west'),
    'minecraft:oak_fence': ('north', 'east', 'south', 'west'),
    'minecraft:oak_slab': ('type',),
    'minecraft:oak_stairs': ('facing', 'half', 'shape'),
}


def normalized_shape_key(block_type: str, state: BlockStateKey) -> Optional[BlockShapeKey]:
    relevant = RELEVANT_PROPERTIES.get(block_type)
    if relevant is None:
        return None

    properties = dict(state)
    if any(key not in properties for key in relevant):
        return None

    return block_type, _state_key(*((key, properties[key]) for key in relevant))


@dataclass
class BlockShapeCatalog:
    shape_catalog_version: int = SHAPE_CATALOG_VERSION
    block_shape_mapping_version: int = BLOCK_SHAPE_MAPPING_VERSION
    cache: Dict[Optional[str], int] = field(default_factory=dict)

    @property
    def catalog_version(self) -> int:
        return self.shape_catalog_version

    def shape_id(self, block_string: Optional[str]) -> int:
        if block_string in self.cache:
            return self.cache[block_string]

        shape_id = self._shape_id_uncached(block_string)
        self.cache[block_string] = shape_id
        return shape_id

    def _shape_id_uncached(self, block_string: Optional[str]) -> int:
        block_type, state = parse_block_state(block_string)
        if block_type in EMPTY_BLOCKS:
            return SHAPE_EMPTY

        key = normalized_shape_key(block_type, state)
        if key is None:
            return SHAPE_FULL_CUBE

        return SHAPE_ID_BY_BLOCK_STATE.get(key, SHAPE_FULL_CUBE)

    def encode_region(
        self,
        side: int,
        block_strings: Sequence[Optional[str]],
    ) -> EncodedBlockRegion:
        expected_count = side * side * side
        if expected_count != len(block_strings):
            raise ValueError(
                f"Expected {expected_count} block strings for side={side}, "
                f"got {len(block_strings)}"
            )

        return EncodedBlockRegion(
            shape_catalog_version=self.shape_catalog_version,
            block_shape_mapping_version=self.block_shape_mapping_version,
            side=side,
            shape_ids=[self.shape_id(block_string) for block_string in block_strings],
        )


DEFAULT_CATALOG = BlockShapeCatalog()
